@startuml
'https://plantuml.com/use-case-diagram

left to right direction
"Utente" as nobody

nobody --> (Como utente do sistema pretendo requisitar uma tarefa indicando os parâmetros necessários à sua execução, nomeadamente o ponto inicial e o término e qual a tarefa pretendida)

@enduml
