@startuml Process View - Level 1 - Create a robot
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title Create a robot

participant "System" as Sys <<System>>

?o->> Sys : POST

activate Sys

?o<<--Sys : 201 Created

deactivate Sys

@enduml
