@startuml Process View - Level 2 - List all passageways
'https://plantuml.com/sequence-diagram

autonumber

skinparam packageStyle rect

title List all passageways

actor "Campus Manager" as CM
participant "Visualization" as V <<Component>>

CM->> V : wants to list all passageways

activate CM
activate V
CM<<-- V : lists all passageways
deactivate V
deactivate CM

@enduml