@startuml Process View - Level 3 - List all passageways
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title List all passageways

actor "Campus Manager" as CM
participant "Routing" as routing <<component>>
participant "Component" as comp <<component>>
participant "Service" as service <<component>>


CM->> routing : GET
activate CM
activate routing
routing ->> comp : list all passageways

activate comp
comp ->> service : list all passageways

activate service
service --> : HttpRequest
service<<--  : HttpResponse
comp <<-- service : HttpResponse
comp ->> service: HttpResponse to list
comp <<-- service : List
deactivate service

comp -->> routing : success
deactivate comp

CM<<-- routing : 200 OK
deactivate routing
deactivate CM

@enduml