@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title Create a floor in a building

actor "Campus Manager" as CM
participant "Visualization" as MD <<Component>>

activate CM
CM->> MD : POST

activate MD
CM<<--MD : 201 Created

deactivate MD


@enduml
