@startuml Process View - Level 3

autonumber
skinparam packageStyle rect

title Edit my data (utente)

participant "Routing" as routing <<component>>
participant "Controller" as controller <<component>>
participant "Service" as service <<component>>
participant "User Repository" as userrepo <<component>>
participant "User" as user <<component>>
participant "Map" as map <<component>>
participant "DTO" as dto <<component>>
database "Database" as db <<component>>

?o->> routing : PATCH
activate routing
routing ->> controller : edit a user data

activate controller
controller ->> service : edit a user data

activate service
service ->> userrepo : getUserByEmail

activate userrepo
userrepo ->> db : select email
activate db
db -->> userrepo : email
deactivate db

userrepo -->> service : email found
deactivate userrepo


service ->> user** : edit
activate user

user -->> user: verifies

user -->> service : edited
deactivate user

service ->> userrepo : save
userrepo ->> db : insert user
activate db
db -->> userrepo : success
deactivate db

userrepo -->> service : success
deactivate userrepo

service ->> map : convert to DTO
activate map

map -->> dto** : convert
activate dto

dto -->> map : dto
deactivate dto

map -->> service : dto
deactivate map

service -->> controller : success
deactivate service

controller -->> routing : success
deactivate controller

?o<<-- routing : 204 Edited
deactivate routing

@enduml