@startuml
'https://plantuml.com/sequence-diagram

autonumber

skinparam packageStyle rect

title edit a building

participant "MasterData" as MD <<Component>>

?o->> MD : PATCH

activate MD
?o<<-- MD : 204|400
deactivate MD
@enduml
