@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title Edit a building

participant "System" as Sys <<System>>

?o->> Sys : PATCH

activate Sys
alt Edit
   ?o<<--Sys : 204 Edited
end
alt Bad Request
   ?o<<--Sys : 400 Bad Request
end
deactivate Sys


@enduml
