@startuml
'https://plantuml.com/component-diagram


top to bottom direction

RobDroneGo <<System>>
component RobDroneGo{
component MasterData <<Component>>{
component BE <<Component>>
component BD <<Component>>
}
port " " as APIPort
}

BE -(0- BD
BE -- APIPort
API -- APIPort

@enduml
