@startuml
'https://plantuml.com/sequence-diagram

autonumber

skinparam packageStyle rect

title List buildings with min and max floors

actor "Campus Manager" as CM
participant "Visualization" as MD <<Component>>

activate CM
CM->> MD : Navigate to listBuildings page

activate MD
CM<<--- MD : Successfully response
deactivate MD
@enduml
