@startuml Process View - Level 2 - Create a passageway
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title Create a passageway

participant "InformationManager" as IM <<Component>>

?o->> IM : POST

activate IM

?o<<--IM : 201 Created

deactivate IM
@enduml
