@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title List all buildings by min max floors

participant "System" as Sys <<System>>

?o->> Sys : GET

activate Sys
?o<<-- Sys : 201 OK
deactivate Sys


@enduml
