@startuml Process View - Level 3 - Edit a building

autonumber
skinparam packageStyle rect

title Edit a building

actor "Campus Manager" as CM <<Human>>
participant "View" as view <<component>>
participant "ViewModel" as viewModel <<component>>
participant "Service" as service <<component>>
participant "HttpAdapter" as httpAdapter <<component>>

activate CM
CM -> view : Navigate to EditBuilding
activate view
view --> CM : Display form for building details
CM -> view : Enters building information

view -> viewModel : Trigger edit building with provided information

activate viewModel
viewModel -> service : Request to edit building

activate service
service -> httpAdapter : Make HTTP Request
activate httpAdapter
httpAdapter ->> : HTTP Request (PATCH)
httpAdapter <<-- : HTTP Response (200)
httpAdapter --> service : Receive HTTP Response
deactivate httpAdapter

service --> viewModel : Receive success response
deactivate service

viewModel --> view : Receive success response
deactivate viewModel

view --> CM : Edited successfully
deactivate view

deactivate CM
@enduml
