@startuml Process View - Level 3

autonumber
skinparam packageStyle rect

title List all floors of a building

actor "Campus Manager" as CM
participant "View" as view <<component>>
participant "ViewModel" as viewModel <<component>>
participant "Service" as service <<component>>
participant "HttpAdapter" as httpAdapter <<component>>

activate CM
CM -> view : Navigate to ListFloors page
activate view
view -> viewModel : Trigger list all floors of a building

activate viewModel
viewModel -> service : Request to list all floors of a building

activate service
service -> httpAdapter : Make HTTP Request
activate httpAdapter
httpAdapter --> service : HTTP Response
deactivate httpAdapter

service --> viewModel : Receive HttpResponse
deactivate service
viewModel --> view : Receive List
deactivate viewModel

CM <-- view : Successfully response
deactivate view
deactivate CM
@enduml
