@startuml Process View - Level 3

autonumber
skinparam packageStyle rect

title List all floors of a building

actor "Campus Manager" as CM
participant "Routing" as routing <<component>>
participant "Component" as comp <<component>>
participant "Service" as service <<component>>

activate CM
CM->> routing : Navigate to ListFloors page
activate routing
routing ->> comp : list all floors of a building

activate comp
comp ->> service : list all floors of a building

activate service
service --> : HttpRequest
service<<--  : HttpResponse
comp <<-- service : HttpResponse
comp ->> service: HttpResponse to list
comp <<-- service : List
deactivate service

comp -->> routing : success
deactivate comp

CM<<-- routing : Successfully response
deactivate routing

@enduml
