@startuml
'https://plantuml.com/sequence-diagram

autonumber

skinparam packageStyle rect

title List all floors of a building

actor "Campus Manager" as CM
participant "Visualization" as MD <<Component>>

activate CM
CM->> MD : GET

activate MD
CM<<-- MD : 200 OK
deactivate MD
@enduml
