@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title list all buildings by min max floors

participant "System" as Sys <<System>>

?o->> Sys : GET

activate Sys
?o<<-- Sys : 201|404
deactivate Sys


@enduml
