@startuml Process View - Level 3

autonumber
skinparam packageStyle rect

title Create a room in a floor

participant "Routing" as routing <<component>>
participant "Component" as comp <<component>>
participant "Service" as service <<component>>

?o->> routing : POST
activate routing
routing ->> comp : create room

activate comp
comp ->> service : create room

activate service
service ->> : Http Request
service <<-- : Http Response

service -->> comp : success
deactivate service

comp -->> routing : success
deactivate comp

?o<<-- routing : 201 Created
deactivate routing

@enduml