@startuml Process View - Level 3 - List all floors with passageways of a building

autonumber
skinparam packageStyle rect

title List all floors with passageways of a building

actor "Campus Manager" as CM
participant "Routing" as routing <<component>>
participant "Component" as comp <<component>>
participant "Service" as service <<component>>

CM->> routing : GET /:buildingCode
activate CM
activate routing
routing ->> comp : list all floors with passageways of a building

activate comp
comp ->> service : list all floors with passageways of a building

activate service
service --> : HttpRequest
service<<--  : HttpResponse
comp <<-- service : HttpResponse
comp ->> service: HttpResponse to list
comp <<-- service : List
deactivate service

comp -->> routing : success
deactivate comp

CM<<-- routing : 200 OK
deactivate routing
deactivate CM

@enduml