@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title Create a Floor Map

participant "Visualization" as MD <<Component>>

?o->> MD : Post

activate MD
?o<<--- MD : 201 Created
deactivate MD
@enduml
