@startuml Process View - Level 3

autonumber
skinparam packageStyle rect

title list all robot of the fleet

participant "Routing" as routing <<component>>
participant "Component" as comp <<component>>
participant "Service" as service <<component>>


?o->> routing : GET
activate routing
routing ->> comp : list all robot of the fleet

activate comp
comp ->> service : list all robot of the fleet

activate service
service --> : HttpRequest
service<<--  : HttpResponse
comp <<-- service : HttpResponse
comp ->> service: HttpResponse to list
comp <<-- service : List

deactivate service

comp -->> routing : success
deactivate comp

?o<<-- routing : 200 OK
deactivate routing

@enduml
