@startuml Process View - Level 3

autonumber
skinparam packageStyle rect

title Inhibit a robot

participant "Routing" as routing <<component>>
participant "Controller" as controller <<component>>
participant "Service" as service <<component>>
participant "Repository" as robotrepo <<component>>
participant "Robot" as robot <<component>>
participant "Map" as map <<component>>
participant "DTO" as dto <<component>>
database "Database" as db <<component>>

?o->> routing : PATCH /robot/:id
activate routing
routing ->> controller : disable robot

activate controller
controller ->> service : disable robot

activate service
service ->> robotrepo : verifies if exists robot with that code

activate robotrepo
robotrepo ->> db : select robot
activate db
db -->> robotrepo : robot
deactivate db
alt robot not found
    robotrepo -->> service :  not found

    service -->> controller : fail
    controller -->> routing : fail
    ?o<<-- routing : 400 Bad Request
end alt

deactivate robotrepo

service ->> robot : inhibit robot
activate robot

robot -->> robot: verifies data

deactivate robot
robot --->> service: robot





service ->> robotrepo : save
activate robotrepo

robotrepo ->> db : insert robot

activate db
db -->> robotrepo : success

deactivate db
robotrepo -->> service : success
deactivate robotrepo

service ->> map: toDTO
activate map
map ->> dto**: dto
activate dto
dto -->> map: dto
deactivate dto
map-->> service: dto
deactivate map


deactivate robotrepo

service -->> controller : success
deactivate service

controller -->> routing : success
deactivate controller

?o<<-- routing : 204 Created
deactivate routing

@enduml
