@startuml Process View - Level 3

autonumber
skinparam packageStyle rect

title list all robots of the fleet

actor "Fleet Manager" as FM
participant "View" as view <<component>>
participant "ViewModel" as viewModel <<component>>
participant "Service" as service <<component>>
participant "HttpAdapter" as httpAdapter <<component>>

activate FM
FM -> view : Navigate to ListAllRobots page
activate view
view -> viewModel : Trigger list all robots of the fleet

activate viewModel
viewModel -> service : Request to list all robots of the fleet

activate service
service -> httpAdapter : HTTP Request
activate httpAdapter
httpAdapter --> service : HTTP Response
deactivate httpAdapter

service --> viewModel : Receive HttpResponse
deactivate service
viewModel --> view : Receive List
deactivate viewModel

FM <-- view : Successfully response
deactivate view
deactivate FM
@enduml
