@startuml
'https://plantuml.com/sequence-diagram

autonumber

skinparam packageStyle rect

title List all passageways

participant "MasterData" as MD <<Component>>

?o->> MD : GET

activate MD
alt Created
   ?o<<--MD : 201 Created
end
alt Bad Request
   ?o<<--MD : 400 Bad Request
end
deactivate MD
@enduml
