@startuml Process View - Level 3

autonumber
skinparam packageStyle rect

title List all passageways

participant "Back-End" as BE <<component>>
database "Database" as DB <<component>>

?o-> BE : GET

activate BE

BE -> DB : select passageways
activate DB
DB --> BE
deactivate DB

?o<- BE : 200 OK

alt bad request / passageways not found
?o<- BE : 400 Bad Request
deactivate BE
end

@enduml
