@startuml Process View - Level 3 - Create a lift

autonumber
skinparam packageStyle rect

title Create a lift

actor "Campus Manager" as CM
participant "Routing" as routing <<component>>
participant "Component" as comp <<component>>
participant "Service" as service <<component>>

CM->> routing : Navigate to CreateLift
activate CM
activate routing
routing ->> comp : create lift

activate comp
comp ->> service : create lift

activate service
service ->> : Http Request
service <<-- : Http Response

service -->> comp : success
deactivate service

comp -->> routing : success
deactivate comp

CM<<-- routing : Successfully response
deactivate routing
deactivate CM
@enduml