@startuml Process View - Level 3

autonumber
skinparam packageStyle rect

title Create a room in a floor

actor "Campus Manager" as CM
participant "Routing" as routing <<component>>
participant "Component" as comp <<component>>
participant "Service" as service <<component>>

activate CM
CM->> routing : POST
activate routing
routing ->> comp : create room

activate comp
comp ->> service : create room

activate service
service ->> : Http Request
service <<-- : Http Response

service -->> comp : success
deactivate service

comp -->> routing : success
deactivate comp

CM<<-- routing : 201 Created
deactivate routing

@enduml