@startuml
'https://plantuml.com/sequence-diagram

autonumber

skinparam packageStyle rect

title List all buildings

participant "MasterData" as MD <<Component>>

?o->> MD : GET

activate MD
alt List
   ?o<<--MD : 200 Listed
end
alt Bad Request
   ?o<<--MD : 400 Bad Request
end
deactivate MD
@enduml
