@startuml Process View - Level 3

autonumber
skinparam packageStyle rect

title Inhibit a robot

participant "Back-End" as BE <<component>>
database "Database" as DB <<component>>

?o->> BE : PATCH

activate BE

BE ->> DB : select robot
activate DB
DB -->> BE
deactivate DB
BE ->> DB : edit robot
activate DB
DB -->> BE
deactivate DB
BE ->> DB : persist robot
activate DB
DB -->> BE
deactivate DB

?o<<- BE : 204 OK

alt bad request / robot does not exist
?o<<- BE : 400 Bad Request
deactivate BE
end

@enduml
