@startuml Process View - Level 3 - Edit a passageway

autonumber
skinparam packageStyle rect

title Edit a passageway

actor "Campus Manager" as CM <<Human>>
participant "View" as view <<component>>
participant "ViewModel" as viewModel <<component>>
participant "Service" as service <<component>>
participant "HttpAdapter" as httpAdapter <<component>>

CM -> view : Wants to edit passageway
activate CM
activate view
view --> CM : Display form for passageway details
CM -> view : Enters passageway information

view -> viewModel : Trigger edit passageway with provided information

activate viewModel
viewModel -> service : Request to edit passageway

activate service
service -> httpAdapter : Make HTTP Request
activate httpAdapter
httpAdapter ->> : HTTP Request (PATCH)
httpAdapter <<-- : HTTP Response (200)
httpAdapter --> service : Receive HTTP Response
deactivate httpAdapter

service -->> viewModel : Receive success response
deactivate service

viewModel -->> view : Receive success response
deactivate viewModel

view --> CM : Success message
deactivate view

deactivate CM
@enduml
