@startuml Process View - Level 2 - Edit a passageway
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title Edit a passageway

actor "Campus Manager" as CM
participant "Visualization" as V <<Component>>

CM->> V : wants to edit a passageway

activate CM
activate V
CM<<-- V : asks to fill a form
CM->> V : fills the form
CM<<--- V : success message
deactivate V
deactivate CM

@enduml