@startuml Process View - Level 3 - Edit a passageway

autonumber
skinparam packageStyle rect

title Edit a passageway

actor "Campus Manager" as CM
participant "Routing" as routing <<component>>
participant "Component" as comp <<component>>
participant "Service" as service <<component>>


CM->> routing : wants to edit passageway
activate CM
activate routing
routing ->> comp : edit passageway

activate comp
comp ->> service : edit passageway

service ->> : Http request (PATCH)
service <<-- : Http response (200)

service -->> comp : success
deactivate service

comp -->> routing : success
deactivate comp

CM<<-- routing : success message
deactivate routing
deactivate CM

@enduml