@startuml
'https://plantuml.com/sequence-diagram

autonumber

skinparam packageStyle rect

title List all buildings min and max floors

participant "Information Manager" as MD <<Component>>

?o->> MD : GET

activate MD
?o<<-- MD : 201 OK
deactivate MD
@enduml
