@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title Edit a lift

participant "Visualization" as MD <<Component>>

?o->> MD : PATCH

activate MD
?o<<--- MD : 201 OK
deactivate MD
@enduml
