@startuml

folder RobDroneGO {
  folder Infrastructure as infra {
    folder Routes as routes {

    }

    folder Persistence as persistence {

    }
  }

  folder "Interface Adapters" as adapters {
    folder Controllers as ctrl {

    }

    folder Repositories as repos {

    }
  }

  folder "Application Services / Use Case Services" as services {
    folder "App Services" as appServ {
    }
  }

  folder Domain as domain {
    folder Aggregates as aggregates {

    }

    folder ValueObjects as vo {

    }

    folder "Domain Services" as domainServ {

    }
  }
}

routes ..> ctrl

ctrl ..> appServ

appServ ..> aggregates
appServ ..> vo
appServ ..> domainServ

repos .u.> persistence
repos ..|> appServ
@enduml
