@startuml Process View - Level 3

autonumber
skinparam packageStyle rect

title Create a robot

participant "Back-End" as BE <<component>>
database "Database" as DB <<component>>

?o-> BE : POST

activate BE

BE -> DB : persist
activate DB
DB --> BE
deactivate DB

?o<- BE : 201 Created

alt bad request / robot already exists
?o<- BE : 400 Bad Request
deactivate BE
end

@enduml
