@startuml Process View - Level 3

autonumber
skinparam packageStyle rect

title Create a robot

participant "Routing" as routing <<component>>
participant "Controller" as controller <<component>>
participant "Service" as service <<component>>
participant "Robot Repository" as robotrepo <<component>>
participant "RobotType Repository" as robottyperepo <<component>>
participant "Robot" as robot <<component>>
participant "Map" as map <<component>>
participant "DTO" as dto <<component>>
database "Database" as db <<component>>

?o->> routing : POST
activate routing
routing ->> controller : create robot

activate controller
controller ->> service : create robot

activate service
service ->> robotrepo : verifies if robot \n already exists

activate robotrepo
robotrepo ->> db : select robot
activate db
db -->> robotrepo : robot
deactivate db

alt robot found
    robotrepo -->> service : robot found
    service -->> controller : fail
    controller -->> routing : fail
    ?o<<-- routing : 400 Bad Request
end alt

robotrepo -->> service : robot not found
deactivate robotrepo

service ->> robottyperepo : verifies if robottypes exists
activate robottyperepo
robottyperepo ->> db : select robottypes
activate db
db -->> robottyperepo : robottypes
deactivate db

alt robottypes not found
    robottyperepo -->> service : robottypes not found
    service -->> controller : fail
    controller -->> routing : fail
    ?o<<-- routing : 404 Not Found
end alt

robottyperepo -->> service : robottypes found
deactivate robottyperepo

service ->> robot** : create
activate robot

robot -->> robot: verifies

alt robot not valid
    robot -->> service : robot not valid
    service -->> controller : fail
    controller -->> routing : fail
    ?o<<-- routing : 400 Bad Request
end alt

robot -->> service : created
deactivate robot

service ->> robotrepo : save
robotrepo ->> db : insert robot
activate db
db -->> robotrepo : success
deactivate db

robotrepo -->> service : success
deactivate robotrepo

service ->> map : convert to DTO
activate map

map -->> dto** : convert
activate dto

dto -->> map : dto
deactivate dto

map -->> service : dto
deactivate map

service -->> controller : success
deactivate service

controller -->> routing : success
deactivate controller

?o<<-- routing : 201 Created
deactivate routing

@enduml
