@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title Create a floor in a building

actor "Fleet Manager" as FM <<Human>>
participant "Visualization" as MD <<Component>>

activate FM
FM->> MD : POST

activate MD
FM<<--MD : 201 Created

deactivate MD


@enduml
