@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title Create a floor in a building

actor "Fleet Manager" as FM <<Human>>
participant "Visualization" as MD <<Component>>

activate FM
FM->> MD : Navigate to createFloor page

activate MD
FM<<--MD : Successfully response

deactivate MD


@enduml
