@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title List all buildings

actor "Campus Manager" as CM
participant "System" as Sys <<System>>

CM->> Sys : GET

activate Sys
activate CM
alt List
   CM<<--Sys : 200 Listed
end
alt Bad Request
   CM<<--Sys : 400 Bad Request
end
activate CM
deactivate Sys


@enduml
