@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title Create a task request

actor "User" as NU
participant "Visualization" as MD <<Component>>

activate NU
NU->> MD : Navigate to task request page

activate MD
NU<<--MD : Successfully response

deactivate MD


@enduml

