@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title List all floors with passageways of a building

actor "Campus Manager" as CM
participant "System" as Sys <<System>>

CM->> Sys : GET /:buildingCode

activate CM
activate Sys

CM<<--Sys : 200 OK

deactivate Sys
deactivate CM

@enduml
