@startuml Process View - Level 3 - Create a passageway

autonumber
skinparam packageStyle rect

title Create a passageway

actor "Campus Manager" as CM <<Human>>
participant "Routing" as routing <<component>>
participant "Component" as comp <<component>>
participant "Service" as service <<component>>

CM->> routing : POST
activate CM
activate routing
routing ->> comp : create passageway

activate comp
comp ->> service : create passageway

activate service
service ->> : Http Request
service <<-- : Http Response

service -->> comp : success
deactivate service

comp -->> routing : success
deactivate comp

CM<<-- routing : 201 Created
deactivate routing
deactivate CM

@enduml