@startuml Process View - Level 2 - Create a passageway
'https://plantuml.com/sequence-diagram

autonumber

skinparam packageStyle rect

title Create a passageway

actor "Campus Manager" as CM <<Human>>
participant "Visualization" as V <<Component>>

CM->> V : wants to create a passageway

activate CM
activate V
CM<<--- V : success message
deactivate V
deactivate CM

@enduml
