@startuml Process View - Level 1 - Create a passageway
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title Create a passageway

actor "Campus Manager" as CM <<Human>>
participant "System" as Sys <<System>>

CM->> Sys : wants to create a passageway

activate CM
activate Sys

CM<<--Sys : success message

deactivate Sys
deactivate CM

@enduml
