@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title Create a passageway

participant "System" as Sys <<System>>

?o->> Sys : POST

activate Sys
?o<<-- Sys : 201|400
deactivate Sys


@enduml
