@startuml Process View - Level 3

autonumber
skinparam packageStyle rect

title Create a user account (user)

actor "New User" as NU
participant "View" as view <<component>>
participant "ViewModel" as viewModel <<component>>
participant "Service" as service <<component>>
participant "HttpAdapter" as httpAdapter <<component>>

activate NU
NU-> view : Navigate to sign up page
activate view
view --> NU : Display form for sign up details
NU -> view : Enters sign up information
view -> viewModel : Trigger sign up with provided information
activate viewModel
viewModel -> service : Request to create user
activate service
service -> httpAdapter : Make HTTP Request
activate httpAdapter
httpAdapter ->> : HTTP Request (POST)
httpAdapter <<-- : HTTP Response (201)
httpAdapter --> service : Receive HTTP Response
deactivate httpAdapter
service --> viewModel : Receive success response
deactivate service
viewModel --> view : Receive success response
deactivate viewModel
view --> NU : Successfully created user
deactivate view
@enduml