@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title Edit a lift

participant "System" as Sys <<System>>

?o->> Sys : PATCH

activate Sys
?o<<--- Sys : 201|400
deactivate Sys

@enduml
