@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title Edit floor of a building

participant "MasterData" as MD <<Component>>

?o->> MD : PATCH

activate MD
?o<<--- MD : 201|400
deactivate MD
@enduml
