@startuml Process View - Level 3

autonumber
skinparam packageStyle rect

title Edit a lift

participant "Back-End" as BE <<component>>
database "Database" as DB <<component>>

?o->> BE : PATCH

activate BE

BE ->> DB : select existing lift
activate DB
DB -->> BE
deactivate DB

BE ->> DB : select floors
activate DB
DB -->> BE
deactivate DB

BE ->> DB : persist
activate DB
DB -->> BE
deactivate DB

?o<<- BE : 200 OK

alt bad request / lift not found / floors not found
?o<<- BE : 400 Bad Request
deactivate BE
end

@enduml
