@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title Create a lift

participant "MasterData" as MD <<Component>>

?o->> MD : POST

activate MD
alt Created
   ?o<<--MD : 201 Created
end
alt Bad Request
   ?o<<--MD : 400 Bad Request
end
deactivate MD


@enduml
