@startuml Process View - Level 3

autonumber
skinparam packageStyle rect

title Create a FloorMap

actor "Campus Manager" as CM
participant "Routing" as routing <<component>>
participant "Component" as comp <<component>>
participant "Service" as service <<component>>

activate CM
CM->> routing : Navigate to FloorMap page
activate routing
routing ->> comp : create FloorMap

activate comp
comp ->> service : create FloorMap

service ->> : Http request
service <<-- : Http response

service -->> comp : success
deactivate service

comp -->> routing : success

CM<<-- routing :Successfully response
deactivate routing

@enduml
