@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title Load floor map

actor "Campus Manager" as CM
participant "RobDroneGO" as Sys <<System>>

activate CM
CM->> Sys : POST

activate Sys
CM<<-- Sys : 201 Created
deactivate Sys


@enduml
