@startuml Process View - Level 3

autonumber
skinparam packageStyle rect

title Create a room in a floor

participant "Routing" as routing <<component>>
participant "Controller" as controller <<component>>
participant "Service" as service <<component>>
participant "Room Repository" as roomrepo <<component>>
participant "Floor Repository" as floorrepo <<component>>
participant "Room" as room <<component>>
participant "Map" as map <<component>>
participant "DTO" as dto <<component>>
database "Database" as db <<component>>

?o->> routing : POST
activate routing
routing ->> controller : create a room in a floor

activate controller
controller ->> service : create a room in a floor

activate service
service ->> roomrepo : verifies if room already exists

activate roomrepo
roomrepo ->> db : select room
activate db
db -->> roomrepo : room
deactivate db

roomrepo -->> service : room not found
deactivate roomrepo

service ->> floorrepo : verifies if floor exists
activate floorrepo
floorrepo ->> db : select floor
activate db
db -->> floorrepo : floor
deactivate db

floorrepo -->> service : floor found
deactivate floorrepo


service ->> room** : create
activate room

room -->> room: verifies

room -->> service : created
deactivate room

service ->> roomrepo : save
roomrepo ->> db : insert robot
activate db
db -->> roomrepo : success
deactivate db

roomrepo -->> service : success
deactivate roomrepo

service ->> map : convert to DTO
activate map

map -->> dto** : convert
activate dto

dto -->> map : dto
deactivate dto

map -->> service : dto
deactivate map

service -->> controller : success
deactivate service

controller -->> routing : success
deactivate controller

?o<<-- routing : 201 Created
deactivate routing

@enduml