@startuml Process View - Level 2 - Create a building
'https://plantuml.com/sequence-diagram

autonumber

skinparam packageStyle rect

title Create a building

actor "Campus Manager" as CM
participant "Visualization" as V <<Component>>


CM->> V : Navigate to CreateBuilding
activate CM
activate V
CM<<--- V : Successfully response
deactivate V
deactivate CM
@enduml
