@startuml Process View - Level 3 - Create a building

autonumber
skinparam packageStyle rect

title Create a building
actor "Campus Manager" as CM
participant "Routing" as routing <<component>>
participant "Component" as comp <<component>>
participant "Service" as service <<component>>
activate CM
CM->> routing : Navigate to CreateBuilding
activate routing
routing ->> comp : create building

activate comp
comp ->> service : create building

activate service
service ->> : Http Request
service <<-- : Http Response

service -->> comp : success
deactivate service

comp -->> routing : success
deactivate comp

CM<<-- routing : Successfully Response
deactivate routing
deactivate CM
@enduml