@startuml Process View - Level 2 - Create a building
'https://plantuml.com/sequence-diagram

autonumber

skinparam packageStyle rect

title Create a building

participant "Visualization" as V <<Component>>

?o->> V : POST

activate V
?o<<--- V : 201 OK
deactivate V

@enduml
