@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title Create a robot type

participant "RobDroneGO" as Sys <<System>>

?o->> Sys : POST

activate Sys
?o<<-- Sys : 201 Created
deactivate Sys


@enduml
