@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title Create a lift

participant "System" as Sys <<System>>

?o->> Sys : POST

activate Sys
alt Created
   ?o<<--Sys : 201 Created
end
alt Bad Request
   ?o<<--Sys : 400 Bad Request
end

deactivate Sys


@enduml
