@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title Create a lift

participant "MasterData" as MD <<Component>>

?o->> MD : POST

activate MD
?o<<-- MD : 201|400
deactivate MD


@enduml
