@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title List all floors with passageways of a building

participant "MasterData" as MD <<Component>>

?o->> MD : GET

activate MD
alt OK
   ?o<<--MD : 200 OK
end
alt Bad Request
   ?o<<--MD : 400 Bad Request
end
alt Building/Floor/Passageways not found
   ?o<<--MD : 404 Not Found
end
deactivate MD

@enduml
