@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title List all floors with passageways of a building

participant "MasterData" as MD <<Component>>

?o->> MD : GET

activate MD
?o<<-- MD : 200|400
deactivate MD

@enduml
