@startuml Process View - Level 3

autonumber
skinparam packageStyle rect

title Create request

participant "Routing" as routing <<component>>
participant "Controller" as controller <<component>>
participant "Service" as service <<component>>
participant "Vigilance Task Repository" as userrepo <<component>>
participant "Vigilance TaskRequest" as user <<component>>
participant "Map" as map <<component>>
participant "DTO" as dto <<component>>
database "Database" as db <<component>>

?o->> routing : POST
activate routing
routing ->> controller : create a task request

activate controller
controller ->> service : create a task request

service ->> user** : create
activate user

user -->> user: verifies

user -->> service : created

deactivate user

service ->> userrepo : save
userrepo ->> db : insert task
activate db
db -->> userrepo : success
deactivate db

userrepo -->> service : success
deactivate userrepo

service ->> map : convert to DTO
activate map

map -->> dto** : convert
activate dto

dto -->> map : dto
deactivate dto

map -->> service : dto
deactivate map

service -->> controller : success
deactivate service

controller -->> routing : success
deactivate controller

?o<<-- routing : 201 Created
deactivate routing

@enduml