@startuml Process View - Level 3 - Create a robot

autonumber
skinparam packageStyle rect

title Create a robot

actor "Fleet Manager" as FM
participant "Routing" as routing <<component>>
participant "Component" as comp <<component>>
participant "Service" as service <<component>>

FM->> routing : wants to create a robot
activate FM
activate routing
routing ->> comp : create robot

activate comp
comp ->> service : create robot

activate service
service ->> : Http Request (POST)
service <<-- : Http Response (201)

service -->> comp : success
deactivate service

comp -->> routing : success
deactivate comp

FM<<-- routing : success message
deactivate routing
deactivate FM

@enduml