@startuml Process View - Level 2 - Create a robot
'https://plantuml.com/sequence-diagram

autonumber

skinparam packageStyle rect

title Create a robot

actor "Fleet Manager" as FM
participant "Visualization" as V <<Component>>

FM->> V : POST

activate FM
activate V
FM<<--- V : 201 OK
deactivate V
deactivate FM

@enduml
