@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title Approve/Reject task

participant "Information Manager" as MD <<Component>>

?o->> MD : GET

activate MD
?o<<--- MD : 200 OK
deactivate MD

?o->> MD : POST

activate MD
?o<<--- MD : 201 Created
deactivate MD
@enduml
