@startuml Process View - Level 3

autonumber
skinparam packageStyle rect

title Aprove/reject task

participant "Routing" as routing <<component>>
participant "Controller" as controller <<component>>
participant "Service" as service <<component>>
participant "Task Repository" as robotrepo <<component>>
participant "Map" as map <<component>>
participant "DTO" as dto <<component>>
database "Database" as db <<component>>

?o->> routing : GET
activate routing
routing ->> controller : list tasks with pending status

activate controller
controller ->> service : list tasks with pending status

activate service
service ->> robotrepo : get list of tasks with pending status

activate robotrepo
robotrepo ->> db : select tasks with pending status
activate db
db -->> robotrepo : list
deactivate db

robotrepo -->> service : list of tasks
deactivate robotrepo

service ->> map : approve/reject
activate map

map -->> dto** : convert
activate dto

dto -->> map : dto list
deactivate dto

map -->> service : dto list
deactivate map

service -->> controller : success
deactivate service

controller -->> routing : success
deactivate controller

?o<<-- routing : 200 OK
deactivate routing

?o->> routing : POST
activate routing
routing ->> controller : received task to aprove or reject

activate controller
controller ->> service :  received task to aprove or reject

activate service
service ->> robotrepo :  find task by id

activate robotrepo
robotrepo ->> db : select task
activate db
db -->> robotrepo : task
deactivate db

robotrepo -->> service : task
deactivate robotrepo

service ->> TaskRequest**: Change state

service ->> Task**:create
service ->> map : convert to DTO
activate map

map -->> dto** : convert
activate dto

dto -->> map : dto
deactivate dto

map -->> service : dto
deactivate map

service -->> controller : success
deactivate service

controller -->> routing : success
deactivate controller

?o<<-- routing : 201 Created
deactivate routing

@enduml
