@startuml Process View - Level 3

autonumber
skinparam packageStyle rect

title Edit a lift

actor "Campus Manager" as CM
participant "View" as view <<component>>
participant "ViewModel" as viewModel <<component>>
participant "Service" as service <<component>>
participant "HttpAdapter" as httpAdapter <<component>>

activate CM
CM -> view : Navigate to editLift page
activate view
view -> viewModel : Trigger edit lift

activate viewModel
viewModel -> service : Request to edit lift

activate service
service -> httpAdapter : HTTP Request
activate httpAdapter
httpAdapter --> service : HTTP Response
deactivate httpAdapter

service -->> viewModel : Receive success response
deactivate service

viewModel -->> view : Receive success response
deactivate viewModel

view --> CM : Successfully response
deactivate view

deactivate CM
@enduml
