@startuml
'https://plantuml.com/sequence-diagram

autonumber
title List all robots from the lit

participant "RobDroneGo" as Sys <<System>>

?o->> Sys : GET

activate Sys
?o<<-- Sys : 201
deactivate Sys
@enduml
