@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title Edit information of a floor

actor "Campus Manager" as CM
participant "System" as Sys <<System>>

activate CM
CM->> Sys : PATCH

activate Sys
CM<<-- Sys : 200 OK
deactivate Sys


@enduml
