@startuml Process View - Level 3

autonumber
skinparam packageStyle rect

title Request the deletion of all my data (user)

actor "New User" as NU
participant "View" as view <<component>>
participant "ViewModel" as viewModel <<component>>
participant "Service" as service <<component>>
participant "HttpAdapter" as httpAdapter <<component>>

activate NU
NU-> view : Navigate to delete page
activate view
view -> viewModel : Trigger delete request
activate viewModel
viewModel -> service : Request to delete
activate service
service -> httpAdapter : Make HTTP Request
activate httpAdapter
httpAdapter ->> : HTTP Request (DELETE)
httpAdapter <<-- : HTTP Response (200)
httpAdapter --> service : Receive HTTP Response
deactivate httpAdapter
service --> viewModel : Receive success response
deactivate service
viewModel --> view : Receive success response
deactivate viewModel
view --> NU : Successfully deleted user
deactivate view
@enduml