@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title Request the deletion of all my data (utente)

actor "User" as NU
participant "Visualization" as MD <<Component>>

activate NU
NU->> MD : Navigate to sign up page

activate MD
NU<<--MD : Successfully response

deactivate MD


@enduml

