@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title List all buildings

participant "System" as Sys <<System>>

?o->> Sys : GET

activate Sys
alt List
   ?o<<--Sys : 200 Listed
end
alt Bad Request
   ?o<<--Sys : 400 Bad Request
end
deactivate Sys


@enduml
