@startuml Process View - Level 3

autonumber
skinparam packageStyle rect

title List all buildings

participant "Routing" as routing <<component>>
participant "Controller" as controller <<component>>
participant "Service" as service <<component>>
participant "Repository" as passagewayrepo <<component>>
participant "Map" as map <<component>>
participant "DTO" as dto <<component>>
database "Database" as db <<component>>

?o->> routing : GET /buildings
activate routing
routing ->> controller : list buildings

activate controller
controller ->> service : list buildings

activate service
service ->> passagewayrepo : get list of buildings

activate passagewayrepo
passagewayrepo ->> db : select all buildings
activate db
db -->> passagewayrepo : list
deactivate db

alt buildings not found
    passagewayrepo -->> service : buildings not found
    service -->> controller : fail
    controller -->> routing : fail
    ?o<<-- routing : 404 Not Found
end alt

passagewayrepo -->> service : list of buildings
deactivate passagewayrepo

service ->> map : convert to DTO List
activate map

map -->> dto** : convert
activate dto

dto -->> map : dto list
deactivate dto

map -->> service : dto list
deactivate map

service -->> controller : success
deactivate service

controller -->> routing : success
deactivate controller

?o<<-- routing : 200 OK
deactivate routing

@enduml
