@startuml DomainModel

skinparam packageStyle rectangle
skinparam linetype ortho
hide methods
hide circle

package User <<aggregate>> {
    class user <<root>>
    class Admin
    class GestorFrota
    class GestorCampus
    class Utente

}

package Edificio <<aggregate>> {
    class edificio <<root>>
    class Piso
    class Corredores
    class Sala
}

class Campus


package Robot <<aggregate>> {
    class robot <<root>>{
        -SerialNumber
        -Marca
        -Id
        -Nickname
        }
    class Droneisep
    class Robisep
enum Função {
    -Entrega
    -Limpeza
    -vigilância
}
}

class Tarefa{

}

user "1" <--- "1" Admin : é
user "1" <-- "1" GestorFrota: é
user "1" <--- "1" GestorCampus: é
user "1" <- "1" Utente: é

Admin "1" --> "1..*" user : gere

Utente "1" --> "1..*" Tarefa : requesita

GestorCampus "1" --> "1..*" Campus : gere

GestorFrota "1" --> "1..*" robot : gere

Campus "1" ---> "5..*" edificio : constituído por

edificio "1" --> "1..*" Piso : têm
Piso "1" --> "1..*" Corredores: têm
Piso "1" --> "1..*" Sala: têm

robot "1"  <-- "1" Droneisep: é
robot "1" <-- "1" Robisep: é


Robisep "1" --> "1..*" Tarefa: realiza
Robisep "1" --> "1" Função : desempenha












@enduml
