@startuml DomainModel

skinparam packageStyle rectangle
skinparam linetype ortho
hide methods
hide circle

package User <<aggregate>> {
    class user <<root>>
    class Admin
    class GestorFrota
    class GestorCampus
    class Utente

}

package Building <<aggregate>> {
    class building <<root>>{
        - Code
        - Name
        - MaxFloorDimension
        - MinFloorDimension
        - Description

    }
    class Lift{
        - Code
        - BuildingCode
    }
}

package Floor <<aggregate>> {
    class floor <<root>>{
        - Code
        - BuildingCode
        - Description
        - FloorDimension
    }

    class Room{
        - Code
        - FloorCode
        - Location
        - Description
        - RoomDimension
    }

    enum Type {
            - Office
            - Amphitheater
            - Laboratory
            - Other
    }

}

package Passageway <<aggregate>>{
    class passageway <<root>>{
        - Code
        - Floor1Code
        - Floor2Code
        - Description
    }
}



class Campus


package Robot <<aggregate>> {
    class robot <<root>>{
        -SerialNumber
        -Marca
        -Id
        -Nickname
        }
    class Droneisep
    class Robisep
enum Função {
    -Entrega
    -Limpeza
    -vigilância
}
}

class Tarefa{

}

user "1" <--- "1" Admin : é
user "1" <-- "1" GestorFrota: é
user "1" <--- "1" GestorCampus: é
user "1" <- "1" Utente: é

Admin "1" --> "1..*" user : gere

Utente "1" --> "1..*" Tarefa : requesita

GestorCampus "1" --> "1..*" Campus : gere

GestorFrota "1" --> "1..*" robot : gere

Campus "1" ---> "5..*" building : constituído por


building "1" --> "1..*" floor : têm
building "1" --> "0..1" Lift : têm

floor "1" --> "1..*" passageway: têm
floor "1" --> "1..*" Room: têm
Room "1" --> "1" Type: é

robot "1"  <-- "1" Droneisep: é
robot "1" <-- "1" Robisep: é


Robisep "1" --> "1..*" Tarefa: realiza
Robisep "1" --> "1" Função : desempenha












@enduml
