@startuml Process View - Level 1- List all passageways
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title List all passageways

participant "System" as Sys <<System>>

?o->> Sys : GET

activate Sys

?o<<--Sys : 200 OK

deactivate Sys


@enduml
