@startuml Process View - Level 1- List all passageways
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title List all passageways

actor "Campus Manager" as CM
participant "System" as Sys <<System>>

CM->> Sys : GET

activate CM
activate Sys

CM<<--Sys : 200 OK

deactivate Sys
deactivate CM

@enduml
