@startuml Process View - Level 1- List all passageways
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title List all passageways

actor "Campus Manager" as CM
participant "System" as Sys <<System>>

CM->> Sys : wants to list all passageways

activate CM
activate Sys

CM<<--Sys : lists all passageways

deactivate Sys
deactivate CM

@enduml
