@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title Create a user account (utente)

actor "New User" as NU
participant "RobDroneGO" as Sys <<System>>

activate NU
NU->> Sys : POST

activate Sys
NU <<-- Sys : 201 Created
deactivate Sys



@enduml
