@startuml Process View - Level 2 - List all passageways
'https://plantuml.com/sequence-diagram

autonumber

skinparam packageStyle rect

title List all buildings

actor "Campus Manager" as CM
participant "Visualization" as V <<Component>>

CM->> V : Navigate to listAllbuildings page
activate CM
activate V
CM<<-- V : List successfully response
deactivate V
deactivate CM
@enduml