@startuml Process View - Level 3 - List all buildings

autonumber
skinparam packageStyle rect

title List all buildings

actor "Campus Manager" as CM <<Human>>
participant "View" as view <<component>>
participant "ViewModel" as viewModel <<component>>
participant "Service" as service <<component>>
participant "HttpAdapter" as httpAdapter <<component>>

CM -> view : Navigate to listAllbuildings page
activate CM
activate view
view -> viewModel : Trigger list all buildings

activate viewModel
viewModel -> service : Request to list all buildings

activate service
service -> httpAdapter : Make HTTP Request
activate httpAdapter
httpAdapter ->> : HTTP Request (GET)
httpAdapter <<-- : HTTP Response (200)
httpAdapter --> service : Receive HTTP Response
deactivate httpAdapter

service --> viewModel : Receive list of all buildings
deactivate service

viewModel --> view : Receive list of all buildings
deactivate viewModel

view --> CM : List successfully response
deactivate view

deactivate CM
@enduml
