@startuml Process View - Level 3 - List all buildings
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title List all buildings

participant "Routing" as routing <<component>>
participant "Component" as comp <<component>>
participant "Service" as service <<component>>


?o->> routing : GET
activate routing
routing ->> comp : list all buildings

activate comp
comp ->> service : list all buildings

activate service
service --> : HttpRequest
service<<--  : HttpResponse
comp <<-- service : List of all buildings
deactivate service

comp -->> routing : success
deactivate comp

?o<<-- routing : 200 OK
deactivate routing

@enduml