@startuml Process View - Level 1 - Edit a passageway
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title Edit a passageway

actor "Campus Manager" as CM
participant "System" as Sys <<System>>

CM->> Sys : wants to edit a passageway

activate CM
activate Sys

CM<<--Sys : success message

deactivate Sys
deactivate CM

@enduml
