@startuml Process View - Level 3 - List all floors with passageways of a building

autonumber
skinparam packageStyle rect

title List all floors with passageways of a building

participant "Routing" as routing <<component>>
participant "Controller" as controller <<component>>
participant "Service" as service <<component>>
participant "Floor Repository" as floorrepo <<component>>
participant "Passageway Repository" as passagewayrepo <<component>>
participant "Map" as map <<component>>
participant "DTO" as dto <<component>>
database "Database" as db <<component>>

?o->> routing : GET /:buildingCode
activate routing
routing ->> controller : list floors with passageways

activate controller
controller ->> service : list floors with passageways

activate service
service ->> floorrepo : get list of floors

activate floorrepo
floorrepo ->> db : select floors
activate db
db -->> floorrepo : list
deactivate db

floorrepo -->> service : list of floors
deactivate floorrepo

service ->> passagewayrepo : get list of passageways
activate passagewayrepo
passagewayrepo ->> db : select passageways
activate db
db -->> passagewayrepo : list
deactivate db

passagewayrepo -->> service : list of passageways
deactivate passagewayrepo

service ->> service : verifies if passageway's floor is in list of floors

service ->> map : convert to DTO List
activate map

map -->> dto** : convert
activate dto

dto -->> map : dto list
deactivate dto

map -->> service : dto list
deactivate map

service -->> controller : success
deactivate service

controller -->> routing : success
deactivate controller

?o<<-- routing : 200 OK
deactivate routing

@enduml
