@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title Edit a passageway

participant "System" as Sys <<System>>

?o->> Sys : PATCH

activate Sys
?o<<-- Sys : 200|400
deactivate Sys


@enduml
