@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam packageStyle rect

title Edit a passageway

participant "System" as Sys <<System>>

?o->> Sys : PATCH /passageways/:id

activate Sys
alt OK
   ?o<<--Sys : 200 OK
end
alt Bad Request
   ?o<<--Sys : 400 Bad Request
end
alt Passageway/Floor not found
   ?o<<--Sys : 404 Not Found
end
deactivate Sys


@enduml
